### ISSUE TITLE
Implementation deviations

### ISSUE THREAD

**Issue by nicemanis** [LeoniusChen/Attentions-in-Tacotron#1]
Hi, I wanted to ask about some deviations in the GMM implementation.

Mozilla TTS:
```
self.N_a = nn.Sequential(
    nn.Linear(query_dim, query_dim, bias=True),
    nn.ReLU(),
    nn.Linear(query_dim, 3*K, bias=True))
```

This repository:
```
self.mlp = nn.Sequential(
    nn.Linear(query_dim, attn_dim, bias=True),
    nn.Tanh(),
    nn.Linear(attn_dim, 3*K))
```

Why is there a Tanh activation instead of ReLU?

Also, in the alignment calculation:
```
sigma = (F.softplus(sigma_hat) + self.eps).unsqueeze(-1)
delta = F.softplus(delta_hat).unsqueeze(-1)
omega = F.softmax(omega_hat, dim=-1).unsqueeze(-1)
mu = self.mu_prev + delta
alignment = omega / Z * torch.exp(-(self.j - mu)**2 / (sigma**2) / 2)
```
sigma squared is divided by 2 instead of multiplied by 2, as shown in the [DCA paper](https://arxiv.org/abs/1910.10288)
![image](https://user-images.githubusercontent.com/9463816/114174719-ab40b280-9941-11eb-9d93-d4fb99e221fa.png)

Then again, Mozilla TTS alignment calculation looks even more different:
```
# g_t == omega_hat
# b_t == delta_hat
# k_t == sigma_hat

# attention GMM parameters
sig_t = torch.nn.functional.softplus(b_t) + self.eps

mu_t = self.mu_prev + torch.nn.functional.softplus(k_t)
g_t = torch.softmax(g_t, dim=-1) + self.eps

j = self.J[:inputs.size(1)+1]

# attention weights
phi_t = g_t.unsqueeze(-1) * (1 / (1 + torch.sigmoid((mu_t.unsqueeze(-1) - j) / sig_t.unsqueeze(-1))))
```

**Comment by LeoniusChen** [comment]
Hi, @nicemanis 
1. In the DCA paper (as you mentioned), tanh is used as the activation function in Formula (7).
2. Sigma squared is divided by 2 in my codes, 2 is the denominator.
3. Mozilla's implemention is the discrete version of GMM attention (I guess). He claims that this version is the best in his experiments and you can dig it up from here [Mozilla GMM attention description](https://erogol.com/two-methods-for-better-attention-in-tacotron/).

**Comment by nicemanis** [comment]
Ok, thank you for the clarification. Have you experimented with Flowtron before? I'm thinking about adapting GMM or DCA in order to improve the Flowtron's stability.

**Comment by LeoniusChen** [comment]
I have not read that paper (it's on my reading list for a long time). 😭

**Comment by nicemanis** [comment]
Let me know if you ever try it out.
By default it uses the Bahdanau attention and it has an adpated version of the LSA. However, it seems that during training it processes all queries together in a single foraward pass, instead of iterating over each timestep one by one. I'm now trying to adapt your implementation of GMM accordingly.

BTW, thank you for the nice repository of various attention models. Have you had a chance to try them out on Nvidia's Tacotron 2? I'm curious about how each attention model compares in terms of speech quality and robustness.

**Comment by LeoniusChen** [comment]
Yes, I have tried these attentions on Nvidia/Tacotron2 (reduction_factor=5) with Blizzard2013 dataset. GMM attention is robust than others, and SMA produces speech of highest quality.
